[package]
name = "tuesday_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
tuesday_core = { path = "../core" }
ratatui = "0.29.0"
crossterm = "0.28.1"
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.89"

[[bin]]
name = "tuetui"
path = "src/main.rs"
